name: 'comment'
description: 'Action to comment {touchstone} results on the appropriate PR. Needs read/write access.'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret.'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Download artifact'
      id: 'download'
      uses: actions/download-artifact@v6
      with:
        name: pr
        github-token: ${{ inputs.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{github.event.workflow_run.id }}
    - name: 'Comment on PR'
      id: 'comment'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          var fs = require('fs');
          var issue_number = Number(fs.readFileSync('./NR'));
          var body = fs.readFileSync('./info.txt').toString();
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: body
          });
    - uses: actions/github-script@v7
      if: always()
      with:
        script: |
          let url = '${{ github.event.workflow_run.html_url }}'
          let any_failed = ${{ steps.comment.outcome == 'failure' || steps.download.outcome == 'failure' }}
          let state = 'success'
          let description = 'Commenting succeeded!'
          
          if(${{ github.event.workflow_run.conclusion == 'failure'}} || any_failed) {
            state = 'failure'
            description = 'Commenting failed!'
            if(any_failed) {
              url = "https://github.com/${{github.repository}}/actions/runs/" + 
                    "${{ github.run_id }}"
            }
          }

          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ github.event.workflow_run.head_sha}}',
            state: state,
            target_url: url,
            description: description,
            context: 'touchstone comment'
          })
