name: 'receive'
description: 'Action to run {touchstone} benchmarks and upload the results.'
inputs:
  benchmarking_repo:
    description: 'Additional repository required for benchmarking.'
    required: false
  benchmarking_ref:
    description: 'Ref of benchmarking repository.'
    required: false
  benchmarking_path:
    description: 'Path to check out benchmarking repository to.'
    required: false
  cache-version:
    description: 'Integer to use as cache version. Increment to use new cache.'
    required: true
    default: 1
    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Set up git user
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
      shell: bash
    - name: Ensure base branch is fetched
      run: |
        git checkout -b $GITHUB_HEAD_REF # this is current ref. This is required for naming.
        git branch $GITHUB_BASE_REF remotes/origin/$GITHUB_BASE_REF
      shell: bash
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: ${{ inputs.cache_version }}
        extra-packages: |
          any::ggplot2
          any::dplyr
          any::gert
          any::glue
    - name: Install touchstone
      run: pak::pkg_install("lorenzwalthert/touchstone@main")
      shell: Rscript {0}
    - name: Remove global installation
      run: |
        pkg <- unlist(read.dcf('DESCRIPTION')[, 'Package'])
        if (pkg %in% rownames(installed.packages())) {
          remove.packages(pkg)
          cat('removed package ', pkg, '.', sep = "")
        }
      shell: Rscript {0}
    - name: Checkout benchmarking repo
      if: ${{ inputs.benchmarking_repo != ''}}
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.benchmarking_repo }}
        ref: ${{ inputs.benchmarking_ref }}
        path: ${{ inputs.benchmarking_path }}
    - name: Run benchmarks
      run: touchstone::run_script("touchstone/script.R")
      shell: Rscript {0}
    - name: Save PR number
      run: |
        echo ${{ github.event.number }} > ./touchstone/pr-comment/NR
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: visual-benchmarks
        path: touchstone/plots/
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: touchstone/pr-comment
    - uses: actions/download-artifact@v2
      with:
        name: results
    - name: comment PR
      run: cat touchstone/pr-comment/info.txt
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: touchstone/pr-comment/
