name: Continuous Benchmarks (Comment)

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Continuous Benchmarks (Receive)"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: lorenzwalthert/touchstone/actions/comment@standalone-action
